FROM python:3.7-slim AS build-image

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    default-libmysqlclient-dev \
    gcc \
    libcurl4-openssl-dev \
    libpq-dev \
    libssl-dev \
    python3-dev \
    unixodbc-dev && \
    pip install virtualenv

WORKDIR /usr/src
COPY pip pip
ENV PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1
RUN virtualenv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install \
    -r pip/requirements.txt \
    -r pip/bigquery-requirements.txt \
    -r pip/mssql-requirements.txt \
    -r pip/mysql-requirements.txt \
    -r pip/postgresql-requirements.txt \
    -r pip/test-requirements.txt

FROM python:3.7-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libmariadb-dev-compat \
    libodbc1 \
    libpq5 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build-image /opt/venv /opt/venv

WORKDIR /usr/src
ENV IP_ADDRESS=0.0.0.0 \
    PATH="/opt/venv/bin:$PATH" \
    VIRTUAL_ENV="/opt/venv"
EXPOSE 5000
CMD ["python3.7", "metREx/manage.py", "run"]